### ISSUE TITLE
scenario formats?

### ISSUE THREAD

**Issue by ydhadix** [Arena-Rosnav/arena-rosnav#51]
Running v0.2.2, it seems like there are two different formats for scenario .json files. Some follow the format in SCHEMA.json, but many do not, such as test_scenario. Attempting to run these scenarios gives the following error.

```Traceback (most recent call last):
  File "/home/username/catkin_ws/devel/lib/task_generator/task_generator_node.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/username/catkin_ws/src/arena-rosnav/task_generator/scripts/task_generator_node.py", line 118, in <module>
    task_generator = TaskGenerator()
  File "/home/username/catkin_ws/src/arena-rosnav/task_generator/scripts/task_generator_node.py", line 40, in __init__
    self.task = get_predefined_task("", self.task_mode, self.env_wrapper)
  File "/home/username/catkin_ws/src/arena-rosnav/task_generator/task_generator/tasks/utils.py", line 49, in get_predefined_task
    task = TaskFactory.instantiate(
  File "/home/username/catkin_ws/src/arena-rosnav/task_generator/task_generator/tasks/task_factory.py", line 23, in instantiate
    return simulator(*args, **kwargs)
  File "/home/username/catkin_ws/src/arena-rosnav/task_generator/task_generator/tasks/scenario.py", line 26, in __init__
    super().__init__(obstacles_manager, robot_managers, map_manager, **kwargs)
  File "/home/username/catkin_ws/src/arena-rosnav/task_generator/task_generator/tasks/base_task.py", line 24, in __init__
    self._set_up_robot_managers()
  File "/home/username/catkin_ws/src/arena-rosnav/task_generator/task_generator/tasks/scenario.py", line 94, in _set_up_robot_managers
    self._check_robot_manager_length()
  File "/home/username/catkin_ws/src/arena-rosnav/task_generator/task_generator/tasks/scenario.py", line 99, in _check_robot_manager_length
    scenario_robots_length = len(self.scenario_file["robots"])
KeyError: 'robots'
```

The companion application arena-tools produces files of the second, nonfunctioning format (and have a 'format' field indicating as much).

Am I missing some obvious method to use the provided and generated arena-tools scenarios?

**Comment by linhdoan8** [comment]
Hey, yes we have had multiple formats and are currently updating our companion app to create scenarios in the new format. We will dismiss the arena-tools and instead use [arena-web](app.arena-web.com) to create new scenarios. The update will be announced in the next week. sorry for the confusion.
